
/*
 * < CONFIG DSP Enable
 */
#define CONFIG_DSP_EN 1
#undef  CONFIG_DSP_WITHIN_APP_IMG

/*
 * < CONFIG TrustZone
 */
#undef  CONFIG_TRUSTZONE

/*
 * < CONFIG Link Option
 */
#define CONFIG_IMG1_FLASH 1
#undef  CONFIG_IMG1_SRAM
#define CONFIG_CODE_XIP_DATA_PSRAM 1
#undef  CONFIG_CODE_PSRAM_DATA_SRAM
#undef  CONFIG_CODE_PSRAM_DATA_PSRAM
#undef  CONFIG_CODE_XIP_DATA_SRAM

/*
 * < CONFIG Mass Production
 */
#undef  CONFIG_MP_INCLUDED

/*
 * < CONFIG Shell CMD
 */
#define CONFIG_SUPPORT_ATCMD 1
#define CONFIG_ATCMD_IO_LOGUART 1
#undef  CONFIG_ATCMD_IO_UART
#undef  CONFIG_LONGER_CMD

/*
 * < CONFIG VFS
 */
#define CONFIG_VFS_LITTLEFS_INCLUDED 1
#undef  CONFIG_VFS_FATFS_INCLUDED

/*
 * < CONFIG OTA OPTION
 */
#undef  CONFIG_UPGRADE_BOOTLOADER
#undef  CONFIG_COMPRESS_OTA_IMG

/*
 * < CONFIG Application Processor
 */
#define CONFIG_AP_CORE_KM4 1
#undef  CONFIG_AP_CORE_KR4
#define CONFIG_WIFI_INIC 1

/*
 * < CONFIG BT
 */
#undef  CONFIG_BT_MENU

/*
 * < CONFIG WIFI
 */
#define CONFIG_WLAN_MENU 1
#define CONFIG_WLAN_KM4_AP_KR4_NP 1
#undef  CONFIG_WLAN_KR4_AP_KM4_NP
#undef  CONFIG_WIFI_KM4_SINGLE_CORE
#undef  CONFIG_WIFI_KR4_SINGLE_CORE
#undef  CONFIG_HIGH_TP_TEST
#define CONFIG_WLAN 1
#define CONFIG_AS_INIC_AP 1
#define CONFIG_LWIP_LAYER 1
#undef  CONFIG_ENABLE_WPS
#undef  CONFIG_WIFI_CSI_ENABLE
#undef  CONFIG_WIFI_ANTDIV_ENABLE
#undef  CONFIG_WIFI_11K_ENABLE
#undef  CONFIG_WIFI_11V_ENABLE
#undef  CONFIG_WIFI_11R_ENABLE

/*
 * < CONFIG LWIP
 */
#undef  CONFIG_FAST_DHCP
#undef  CONFIG_LWIP_DEBUG


/*
 * < MENUCONFIG FOR KM4 CONFIG
 */

/*
 * < CONFIG CHIP
 */
#define CONFIG_AMEBALITE 1
#define ARM_CORE_CM4 1
#undef  CONFIG_FPGA

/*
 * < CONFIG OS
 */
#define CONFIG_KERNEL 1
#define PLATFORM_FREERTOS 1
#define TASK_SCHEDULER_DISABLED (0)

/*
 * < CONFIG FUNCTION TEST
 */
#undef  CONFIG_PER_TEST

/*
 * < CONFIG SECURE TEST
 */
#undef  CONFIG_SEC_VERIFY

/*
 * < SSL Config
 */
#define CONFIG_USE_MBEDTLS_ROM 1
#define CONFIG_MBED_TLS_ENABLED 1
#undef  CONFIG_SSL_ROM_TEST

/*
 * < Audio Config
 */
#define CONFIG_AUDIO_FWK 1
#undef  CONFIG_AUDIO_MIXER
#define CONFIG_AUDIO_PASSTHROUGH 1
#define CONFIG_MEDIA_PLAYER 1

/*
 *     Demux
 */
#undef  CONFIG_MEDIA_DEMUX_WAV
#define CONFIG_MEDIA_DEMUX_MP3 1
#undef  CONFIG_MEDIA_DEMUX_AAC
#undef  CONFIG_MEDIA_DEMUX_MP4
#undef  CONFIG_MEDIA_DEMUX_FLAC
#undef  CONFIG_MEDIA_DEMUX_OGG

/*
 *     Codec
 */
#undef  CONFIG_MEDIA_CODEC_PCM
#define CONFIG_MEDIA_CODEC_MP3 1
#undef  CONFIG_MEDIA_CODEC_HAAC
#undef  CONFIG_MEDIA_CODEC_VORBIS
#undef  CONFIG_MEDIA_CODEC_OPUS

/*
 * Third Party Lib
 */
#undef  CONFIG_SPEEX_LIB
#define CONFIG_OPUS_LIB 1
#define CONFIG_AUDIO_FWK 1

/*
 * < GUI Config
 */
#undef  CONFIG_GUI_EN

/*
 * < CONFIG IPC Message Queue
 */
#define CONFIG_IMQ_EN 1
#define CONFIG_RPC_EN 1
#undef  CONFIG_IMQ2_TEST
#define CONFIG_IPC_MSG_MASTER 1

/*
 * < To set debug msg flag
 */
#undef  CONFIG_DEBUG_CRASHDUMP_IMG1

/*
 * < Build Option
 */
#define CONFIG_TOOLCHAIN_ASDK 1
#undef  CONFIG_TOOLCHAIN_ARM_GCC
#undef  CONFIG_LINK_ROM_LIB
#define CONFIG_LINK_ROM_SYMB 1

