/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VOICERPC_SYSTEM_H_RPCGEN
#define _VOICERPC_SYSTEM_H_RPCGEN

#include "rpc_struct.h"

#include "VoiceRPC_System_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <RPCBaseDS.h>
#include <VoiceRPCBaseDS.h>

#define VOICE_SYSTEM 3001
#define VERSION 0

struct REG_STRUCT *VOICE_SYSTEM_0_register(struct REG_STRUCT *rnode);
#define VOICE_RPC_ToAgent_Init 1
extern  VOICE_RPCRES_INIT *VOICE_RPC_ToAgent_Init_0(VOICE_RPC_INIT *, CLNT_STRUCT *);
extern  VOICE_RPCRES_INIT *VOICE_RPC_ToAgent_Init_0_svc(VOICE_RPC_INIT *, RPC_STRUCT *, VOICE_RPCRES_INIT *);
extern  VOICE_RPCRES_INIT *(*p_VOICE_RPC_ToAgent_Init_0_svc)(VOICE_RPC_INIT *, RPC_STRUCT *, VOICE_RPCRES_INIT *);
#define VOICE_RPC_ToAgent_Release 2
extern  HRESULT *VOICE_RPC_ToAgent_Release_0(VOICE_RPC_INSTANCE *, CLNT_STRUCT *);
extern  HRESULT *VOICE_RPC_ToAgent_Release_0_svc(VOICE_RPC_INSTANCE *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_VOICE_RPC_ToAgent_Release_0_svc)(VOICE_RPC_INSTANCE *, RPC_STRUCT *, HRESULT *);
#define VOICE_RPC_ToAgent_Streaming_Process 3
extern  HRESULT *VOICE_RPC_ToAgent_Streaming_Process_0(VOICE_RPC_INSTANCE *, CLNT_STRUCT *);
extern  HRESULT *VOICE_RPC_ToAgent_Streaming_Process_0_svc(VOICE_RPC_INSTANCE *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_VOICE_RPC_ToAgent_Streaming_Process_0_svc)(VOICE_RPC_INSTANCE *, RPC_STRUCT *, HRESULT *);
#define VOICE_RPC_ToAgent_Recognizer_Process 4
extern  HRESULT *VOICE_RPC_ToAgent_Recognizer_Process_0(VOICE_RPC_INSTANCE *, CLNT_STRUCT *);
extern  HRESULT *VOICE_RPC_ToAgent_Recognizer_Process_0_svc(VOICE_RPC_INSTANCE *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_VOICE_RPC_ToAgent_Recognizer_Process_0_svc)(VOICE_RPC_INSTANCE *, RPC_STRUCT *, HRESULT *);
#define VOICE_RPC_ToAgent_Sync_Mic_Data 5
extern  HRESULT *VOICE_RPC_ToAgent_Sync_Mic_Data_0(VOICE_RPC_MIC_DATA *, CLNT_STRUCT *);
extern  HRESULT *VOICE_RPC_ToAgent_Sync_Mic_Data_0_svc(VOICE_RPC_MIC_DATA *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_VOICE_RPC_ToAgent_Sync_Mic_Data_0_svc)(VOICE_RPC_MIC_DATA *, RPC_STRUCT *, HRESULT *);
#define VOICE_RPC_ToAgent_USR_CMD 6
extern  HRESULT *VOICE_RPC_ToAgent_USR_CMD_0(VOICE_RPC_USR_CMD *, CLNT_STRUCT *);
extern  HRESULT *VOICE_RPC_ToAgent_USR_CMD_0_svc(VOICE_RPC_USR_CMD *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_VOICE_RPC_ToAgent_USR_CMD_0_svc)(VOICE_RPC_USR_CMD *, RPC_STRUCT *, HRESULT *);

#ifdef __cplusplus
}
#endif

#endif /* !_VOICERPC_SYSTEM_H_RPCGEN */
