/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <VoiceRPCBaseDS.h>
#include <RPCBaseDS.h>

bool_t
xdr_VOICE_RPC_INSTANCE(XDR *xdrs, VOICE_RPC_INSTANCE *objp)
{
	if (!xdr_long(xdrs, &objp->streaming_ins)) {
		return FALSE;
	}
	if (!xdr_long(xdrs, &objp->recognizer_ins)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_VOICE_RPCRES_INIT(XDR *xdrs, VOICE_RPCRES_INIT *objp)
{
	if (!xdr_HRESULT(xdrs, &objp->rpc_result)) {
		return FALSE;
	}
	if (!xdr_VOICE_RPC_INSTANCE(xdrs, &objp->instance)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_VOICE_RPC_INIT(XDR *xdrs, VOICE_RPC_INIT *objp)
{
	if (!xdr_uint32_t (xdrs, &objp->mic_data_addr)) {
		return FALSE;
	}
	if (!xdr_uint32_t (xdrs, &objp->res_data_addr)) {
		return FALSE;
	}
	if (!xdr_long(xdrs, &objp->mic_data_length)) {
		return FALSE;
	}
	if (!xdr_long(xdrs, &objp->res_data_length)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_VOICE_RPC_MIC_DATA(XDR *xdrs, VOICE_RPC_MIC_DATA *objp)
{
	if (!xdr_uint32_t (xdrs, &objp->data_addr)) {
		return FALSE;
	}
	if (!xdr_long(xdrs, &objp->length)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_VOICE_RPC_STREAMING_RESULT(XDR *xdrs, VOICE_RPC_STREAMING_RESULT *objp)
{
	if (!xdr_long(xdrs, &objp->uv_ret)) {
		return FALSE;
	}
	if (!xdr_uint32_t (xdrs, &objp->out_data_addr)) {
		return FALSE;
	}
	if (!xdr_long(xdrs, &objp->vad_flag)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_VOICE_RPCRES_STREAMING_PROCESS(XDR *xdrs, VOICE_RPCRES_STREAMING_PROCESS *objp)
{
	if (!xdr_HRESULT(xdrs, &objp->rpc_result)) {
		return FALSE;
	}
	if (!xdr_VOICE_RPC_STREAMING_RESULT(xdrs, &objp->streaming_ret)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_VOICE_RPC_RECOGNIZER_INSTANCE(XDR *xdrs, VOICE_RPC_RECOGNIZER_INSTANCE *objp)
{
	if (!xdr_long(xdrs, &objp->instance_id)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_VOICE_RPC_RECOGNIZER_RESULT(XDR *xdrs, VOICE_RPC_RECOGNIZER_RESULT *objp)
{
	if (!xdr_long(xdrs, &objp->uv_ret)) {
		return FALSE;
	}
	if (!xdr_long(xdrs, &objp->word_id)) {
		return FALSE;
	}
	if (!xdr_float(xdrs, &objp->confidence)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_VOICE_RPCRES_RECOGNIZER_PROCESS(XDR *xdrs, VOICE_RPCRES_RECOGNIZER_PROCESS *objp)
{
	if (!xdr_HRESULT(xdrs, &objp->rpc_result)) {
		return FALSE;
	}
	if (!xdr_VOICE_RPC_RECOGNIZER_RESULT(xdrs, &objp->recognizer_ret)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_VOICE_RPC_ERROR_STATE(XDR *xdrs, VOICE_RPC_ERROR_STATE *objp)
{
	if (!xdr_long(xdrs, &objp->type)) {
		return FALSE;
	}
	if (!xdr_long(xdrs, &objp->state)) {
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_VOICE_RPC_USR_CMD(XDR *xdrs, VOICE_RPC_USR_CMD *objp)
{
	if (!xdr_long(xdrs, &objp->magic)) {
		return FALSE;
	}
	if (!xdr_long(xdrs, &objp->cmd)) {
		return FALSE;
	}
	if (!xdr_long(xdrs, &objp->seq)) {
		return FALSE;
	}
	if (!xdr_long(xdrs, &objp->length)) {
		return FALSE;
	}
	if (!xdr_uint32_t (xdrs, &objp->data_addr)) {
		return FALSE;
	}
	return TRUE;
}
