/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VOICERPCBASEDS_H_RPCGEN
#define _VOICERPCBASEDS_H_RPCGEN

#include "rpc_struct.h"

#include "VoiceRPCBaseDS_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <RPCBaseDS.h>

/* the xdr functions */
extern  bool_t xdr_VOICE_RPC_INSTANCE(XDR *, VOICE_RPC_INSTANCE *);
extern  bool_t xdr_VOICE_RPCRES_INIT(XDR *, VOICE_RPCRES_INIT *);
extern  bool_t xdr_VOICE_RPC_INIT(XDR *, VOICE_RPC_INIT *);
extern  bool_t xdr_VOICE_RPC_MIC_DATA(XDR *, VOICE_RPC_MIC_DATA *);
extern  bool_t xdr_VOICE_RPC_STREAMING_RESULT(XDR *, VOICE_RPC_STREAMING_RESULT *);
extern  bool_t xdr_VOICE_RPCRES_STREAMING_PROCESS(XDR *, VOICE_RPCRES_STREAMING_PROCESS *);
extern  bool_t xdr_VOICE_RPC_RECOGNIZER_INSTANCE(XDR *, VOICE_RPC_RECOGNIZER_INSTANCE *);
extern  bool_t xdr_VOICE_RPC_RECOGNIZER_RESULT(XDR *, VOICE_RPC_RECOGNIZER_RESULT *);
extern  bool_t xdr_VOICE_RPCRES_RECOGNIZER_PROCESS(XDR *, VOICE_RPCRES_RECOGNIZER_PROCESS *);
extern  bool_t xdr_VOICE_RPC_ERROR_STATE(XDR *, VOICE_RPC_ERROR_STATE *);
extern  bool_t xdr_VOICE_RPC_USR_CMD(XDR *, VOICE_RPC_USR_CMD *);

#ifdef __cplusplus
}
#endif

#endif /* !_VOICERPCBASEDS_H_RPCGEN */
