/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VOICERPCBASEDS_DATA_H_RPCGEN
#define _VOICERPCBASEDS_DATA_H_RPCGEN

#include <RPCBaseDS.h>

struct VOICE_RPC_INSTANCE {
	long streaming_ins;
	long recognizer_ins;
};
typedef struct VOICE_RPC_INSTANCE VOICE_RPC_INSTANCE;

struct VOICE_RPCRES_INIT {
	HRESULT rpc_result;
	VOICE_RPC_INSTANCE instance;
};
typedef struct VOICE_RPCRES_INIT VOICE_RPCRES_INIT;

struct VOICE_RPC_INIT {
	uint32_t mic_data_addr;
	uint32_t res_data_addr;
	long mic_data_length;
	long res_data_length;
};
typedef struct VOICE_RPC_INIT VOICE_RPC_INIT;

struct VOICE_RPC_MIC_DATA {
	uint32_t data_addr;
	long length;
};
typedef struct VOICE_RPC_MIC_DATA VOICE_RPC_MIC_DATA;

struct VOICE_RPC_STREAMING_RESULT {
	long uv_ret;
	uint32_t out_data_addr;
	long vad_flag;
};
typedef struct VOICE_RPC_STREAMING_RESULT VOICE_RPC_STREAMING_RESULT;

struct VOICE_RPCRES_STREAMING_PROCESS {
	HRESULT rpc_result;
	VOICE_RPC_STREAMING_RESULT streaming_ret;
};
typedef struct VOICE_RPCRES_STREAMING_PROCESS VOICE_RPCRES_STREAMING_PROCESS;

struct VOICE_RPC_RECOGNIZER_INSTANCE {
	long instance_id;
};
typedef struct VOICE_RPC_RECOGNIZER_INSTANCE VOICE_RPC_RECOGNIZER_INSTANCE;

struct VOICE_RPC_RECOGNIZER_RESULT {
	long uv_ret;
	long word_id;
	float confidence;
};
typedef struct VOICE_RPC_RECOGNIZER_RESULT VOICE_RPC_RECOGNIZER_RESULT;

struct VOICE_RPCRES_RECOGNIZER_PROCESS {
	HRESULT rpc_result;
	VOICE_RPC_RECOGNIZER_RESULT recognizer_ret;
};
typedef struct VOICE_RPCRES_RECOGNIZER_PROCESS VOICE_RPCRES_RECOGNIZER_PROCESS;

struct VOICE_RPC_ERROR_STATE {
	long type;
	long state;
};
typedef struct VOICE_RPC_ERROR_STATE VOICE_RPC_ERROR_STATE;

struct VOICE_RPC_USR_CMD {
	long magic;
	long cmd;
	long seq;
	long length;
	uint32_t data_addr;
};
typedef struct VOICE_RPC_USR_CMD VOICE_RPC_USR_CMD;

#endif /* !_VOICERPCBASEDS_DATA_H_RPCGEN */
