.insert <RPCBaseDS.h>
struct VOICE_RPC_INSTANCE
{
	long streaming_ins;
	long recognizer_ins;
};
struct VOICE_RPCRES_INIT
{
	HRESULT rpc_result;
	VOICE_RPC_INSTANCE instance;
};
struct VOICE_RPC_INIT
{
	uint32_t mic_data_addr;
	uint32_t res_data_addr;
	long mic_data_length;
	long res_data_length;
};
struct VOICE_RPC_MIC_DATA
{
	uint32_t data_addr;
	long length;
};
struct VOICE_RPC_STREAMING_RESULT
{
	long uv_ret;
	uint32_t out_data_addr;
	long vad_flag;
};
struct VOICE_RPCRES_STREAMING_PROCESS
{
	HRESULT rpc_result;
	VOICE_RPC_STREAMING_RESULT streaming_ret;
};
struct VOICE_RPC_RECOGNIZER_INSTANCE
{
	long instance_id;
};
struct VOICE_RPC_RECOGNIZER_RESULT
{
	long uv_ret;
	long word_id;
	float confidence;
};
struct VOICE_RPCRES_RECOGNIZER_PROCESS
{
	HRESULT rpc_result;
	VOICE_RPC_RECOGNIZER_RESULT recognizer_ret;
};
struct VOICE_RPC_ERROR_STATE
{
	long type;
	long state;
};

struct VOICE_RPC_USR_CMD
{
	long magic;
	long cmd;
	long seq;
	long length;
	uint32_t data_addr;
};